import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProviderQuery from "./utils/ProviderQuery";
import { GlobalContextProvider } from "./contex/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderQuery>
          <GlobalContextProvider>{children}</GlobalContextProvider>
        </ProviderQuery>
      </body>
    </html>
  );
}
